# We have a conf and classes directory, append to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a recipes directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

# Register layer
BBFILE_COLLECTIONS += "opennow"
BBFILE_PATTERN_opennow = "^${LAYERDIR}/"
BBFILE_PRIORITY_opennow = "6"

LAYERVERSION_opennow = "1"

# Dependencies
LAYERDEPENDS_opennow = "core openembedded-layer meta-python qt6-layer rust-bin-layer clang-layer"

# Yocto release compatibility
LAYERSERIES_COMPAT_opennow = "scarthgap"